backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

x-meta-default: &metaDefault
  widget: 'string'
  required: false

x-widget-md-min: &WidgetMDMin
  widget: 'markdown'
  buttons: ['italic', 'bold', 'link']
  minimal: true
  editorComponents: []

x-meta: &metaAll
  - label: 'Page Title (browser top bar)'
    name: 'title'
    <<: *metaDefault
  - label: 'Meta Description'
    name: 'description'
    <<: *metaDefault
  - label: 'OpenGraph Image'
    name: 'og_image'
    widget: 'image'
    required: false
  - label: 'OpenGraph Title'
    name: 'og_title'
    <<: *metaDefault
  - label: 'OpenGraph Description'
    name: 'og_description'
    <<: *metaDefault
  - label: 'Twitter Image'
    name: 'twitter_image'
    widget: 'image'
    required: false
  - label: 'Twitter Title'
    name: 'twitter_title'
    <<: *metaDefault
  - label: 'Twitter Description'
    name: 'twitter_description'
    <<: *metaDefault
  - label: 'Published at'
    name: 'published_at'
    widget: 'datetime'
  - label: 'Updated at'
    name: 'updated_at'
    widget: 'datetime'

# Collections https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - label: Settings
    name: settings
    files:
      - label: General
        name: general
        format: 'json'
        file: 'content/settings/site-settings.json'
        editor:
          preview: false
        fields:
          - label: Logo
            name: logo
            widget: image
          - label: "Profile"
            name: "nav_left_button"
            widget: "object"
            summary: '{{fields.label}}: {{fields.url}}'
            fields:
              - label: 'Anchor Text'
                name: label
                widget: string
                default: ''
              - label: 'URL excluding batsoc.com.au'
                name: url
                widget: string
                default: '/'
          - label: 'Top Navigation Menu buttons'
            name: 'navigation'
            widget: 'list'
            summary: '{{fields.label}}: {{fields.url}}'
            fields:
              - label: 'URL Anchor'
                name: label
                widget: string
                default: ''
              - label: 'URL excluding batsoc.com.au'
                name: url
                widget: string
                default: '/'
              
          - label: 'Facebook Page slug (not url)'
            name: 'facebook'
            widget: 'string'
          - label: 'Twitter @username (not URL)'
            name: 'twitter'
            widget: 'string'
          - label: 'Instagram @username (not URL)'
            name: 'instagram'
            widget: 'string'
          - label: 'Footer text'
            name: 'footer_text'
            widget: 'string'
          - label: 'Meta Data Defaults'
            name: 'meta'
            widget: 'object'
            fields: *metaAll

  - name: 'pages'
    label: 'Pages'
    folder: 'content/pages'
    create: true
    slug: '{{slug}}'
    format: 'json'
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Subtitle, name: subtitle, widget: text, required: false }
      - { label: Content, name: content, widget: markdown }
      - { label: 'Featured Image', name: featuredImage, widget: image, required: false }
      - { label: 'SEO Description', name: seoDescription, widget: text, required: false }
      - { label: 'SEO Meta Image', name: seoMetaImage, widget: image, required: false }

  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: '{{slug}}'
    format: 'json'
    sort: 'published_at:desc'
    fields:
      - { label: Title, name: title, widget: string }
      - { label: 'Published At', name: publishedAt, widget: date, format: 'Do MMM YYYY' }
      - { label: Content, name: content, widget: markdown }
      - { label: 'Featured Image', name: featuredImage, widget: image, required: false }
      - { label: 'SEO Description', name: seoDescription, widget: text, required: false }
      - { label: 'SEO Meta Image', name: seoMetaImage, widget: image, required: false }